//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Lunary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estabelecimento
    {
        public int ESTABID { get; set; }
        public string ESTABNOME { get; set; }
        public string ESTABENDERECO { get; set; }
        public string ESTABBAIRRO { get; set; }
        public string ESTATELEFONE { get; set; }
        public string ESTABCEP { get; set; }
        public string ESTABLOGIN { get; set; }
        public string ESTABSENHA { get; set; }
        public string ESTATIPO { get; set; }
    }
}
