//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Lunary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estabelecimento
    {
        public int ESTABID { get; set; }
        public string ESTABNOME { get; set; }
        public string ESTABENDERECO { get; set; }
        public string ESTABBAIRRO { get; set; }
        public int ESTATELEFONE { get; set; }
        public int ESTABCEP { get; set; }
        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name = "Usuário:")]
        public string ESTABLOGIN { get; set; }
        [Required(ErrorMessage = "Informe a senha")]
        [Display(Name = "Senha:")]
        public string ESTABSENHA { get; set; }
        public string ESTATIPO { get; set; }
    }
}
