//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Lunary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagens
    {
        public int id { get; set; }
        public string nm_arquivo { get; set; }
        public byte[] vb_imagem { get; set; }
    }
}
